/**
 * ストレッチ内容の英語版
 *
 * 日本語データ(stretches.ts)は一切変更せず、ここに id で対応する英文を置く。
 * getStretchesBySymptom(symptomId, locale) が locale に応じて差し替える。
 *
 * 【英語版で守るルール】
 * - 症状名や病名を「治る/改善する」と断定しない(FTC の健康表示規制)
 *   例: 「ストレートネックの改善」→ 何の筋肉がどう動くかを事実として書く
 * - "cure" "treat" "fix" "heal" "relieve pain" は使わない
 * - 効果は体の動きの説明として書く(loosen / lengthen / range of motion)
 */

export interface StretchText {
  title: string;
  duration: string;
  reps: string;
  steps: string[];
  tips: string;
  benefit: string;
}

export const STRETCHES_EN: Record<string, StretchText> = {
  // ========== Neck ==========
  "neck-1": {
    title: "Side Neck Stretch",
    duration: "20 sec each side",
    reps: "3 sets",
    steps: [
      "Sit back in a chair with your spine tall. Feet hip-width apart, soles flat on the floor.",
      "Rest your right hand gently on the left side of your head. Let the weight of your hand do the work — don't pull.",
      "Breathe out slowly and let your head tip to the right. Feel your left ear move away from your left shoulder.",
      "Stop where you feel a gentle stretch down the left side of your neck. Hold 20 seconds, breathing normally.",
      "Bring your head back to center and take one deep breath. Repeat on the other side (left hand, right side of head) for 20 seconds.",
      "One round each side is a set. Do 3 sets.",
    ],
    tips: "Keep the opposite shoulder pressed down toward the floor so it doesn't ride up with your head.",
    benefit: "Lengthens the muscles along the side of your neck, including the sternocleidomastoid.",
  },
  "neck-2": {
    title: "Neck Circles",
    duration: "30 sec each direction",
    reps: "2 sets",
    steps: [
      "Sit back in a chair, spine tall, shoulders relaxed. Rest your hands on your thighs.",
      "Breathe out and lower your chin toward your chest. Feel the back of your neck lengthen.",
      "From there, roll your head slowly clockwise: right ear toward right shoulder, back, left shoulder, front. Draw one or two large circles over 30 seconds.",
      "Return to center and rest for 5 seconds.",
      "Now roll counter-clockwise (left ear, left shoulder, back, right shoulder, front) for 30 seconds.",
      "One round each direction is a set. Do 2 sets.",
    ],
    tips: "Speed doesn't matter — the feeling of an easy stretch does. Stop before anything hurts.",
    benefit: "Takes your neck through its full range of motion so no one area stays locked up.",
  },
  "neck-3": {
    title: "Chin Tuck",
    duration: "Hold 10 sec",
    reps: "10 reps",
    steps: [
      "Stand with your back against a wall — head, upper back, hips and heels all touching. This is your starting position.",
      "Tuck your chin slightly and press the back of your head into the wall. Think of making a double chin.",
      "Notice the back of your neck lengthening and the top of your head lifting.",
      "Hold for 10 seconds. Keep breathing — don't hold your breath.",
      "Release slowly and let your head return to neutral.",
      "Repeat 10 times.",
    ],
    tips: "Draw your chin straight back, not down. Looking at the floor is a different movement.",
    benefit: "Works the deep flexors at the front of the neck — the muscles that hold your head over your shoulders rather than out in front.",
  },
  "neck-4": {
    title: "Upper Neck Stretch (Levator Scapulae)",
    duration: "20 sec each side",
    reps: "3 sets",
    steps: [
      "Sit back in a chair with your spine tall and shoulders relaxed. Feet flat on the floor.",
      "Turn your head 45 degrees to the right, as if looking at something to your right. This is a rotation, not a tilt — that's the key.",
      "From there, lower your chin toward your right chest. Let your gaze travel down toward your right toes.",
      "Rest your left hand on the back of your head, just above the right ear. Let the weight of your hand press gently — don't pull.",
      "Feel a deep stretch from the left side of the back of your neck down to where it meets your shoulder. Hold 20 seconds.",
      "Return slowly and repeat on the other side (turn 45 degrees left, chin toward left chest) for 20 seconds. One round each side is a set. Do 3 sets.",
    ],
    tips: "Rotate first, then lower. That order is what makes this different from the side tilt — it reaches the deeper muscle underneath.",
    benefit: "Targets the levator scapulae, a deep muscle that runs from your neck to your shoulder blade and is often the one that stays tight.",
  },
  "neck-5": {
    title: "Shoulder Blade Squeeze",
    duration: "Hold 5 sec",
    reps: "15 reps",
    steps: [
      "Sit toward the front of a chair with your spine tall. Let your arms hang naturally.",
      "Bend both elbows to 90 degrees with your palms facing forward.",
      "Draw your elbows back and squeeze your shoulder blades toward your spine.",
      "Open your chest and hold for 5 seconds. Imagine holding something between your shoulder blades.",
      "Release slowly and return your arms to the start.",
      "Repeat 15 times.",
    ],
    tips: "Keep your shoulders down. Move the shoulder blades, not the shoulders.",
    benefit: "Loosens the area around the shoulder blades and takes load off the neck and shoulders.",
  },

  // ========== Shoulder ==========
  "shoulder-1": {
    title: "Shoulder Rolls",
    duration: "30 sec each direction",
    reps: "2 sets",
    steps: [
      "Stand with feet hip-width apart (or sit in a chair) and let your arms hang loose.",
      "Shrug your shoulders up toward your ears, then roll them forward in a big circle.",
      "Go shoulders forward, down, back, up — 5 or 6 full rotations over 30 seconds.",
      "Reverse the direction (back, down, forward, up) for another 30 seconds and 5 or 6 rotations.",
      "Think about your shoulder blades, so your whole upper back moves, not just your shoulders.",
      "Do 2 sets.",
    ],
    tips: "Keep your elbows and hands loose. Make the shoulder blades travel as far as they comfortably can.",
    benefit: "Gets blood moving around the shoulder joint and takes desk-work stiffness out of the area.",
  },
  "shoulder-2": {
    title: "Cross-Body Arm Stretch",
    duration: "20 sec each side",
    reps: "3 sets",
    steps: [
      "Stand with feet hip-width apart, or sit tall in a chair.",
      "Reach your right arm straight across your chest at shoulder height, fingers pointing left.",
      "Use your left hand to hold the outside of your right elbow and draw it toward your body.",
      "Feel the stretch across the back of your right shoulder. Hold 20 seconds.",
      "Release slowly and repeat on the other side (left arm, right hand) for 20 seconds.",
      "One round each side is a set. Do 3 sets.",
    ],
    tips: "Pull only to the point where it feels good, never painful. Think about the outer edge of the shoulder blade.",
    benefit: "Lengthens the back of the shoulder (rear deltoid and the outside of the shoulder blade), so the arm moves more freely.",
  },
  "shoulder-3": {
    title: "Towel Shoulder Stretch",
    duration: "Hold 15 sec",
    reps: "10 reps",
    steps: [
      "Take a long hand towel or bath towel and hold each end, hands wider than shoulder-width.",
      "Stand tall and raise both arms straight overhead, keeping the towel taut.",
      "Without bending your elbows, lower the towel slowly behind you.",
      "If your shoulders are tight, stop early — don't force it. Hold 15 seconds where your shoulder blades come together.",
      "Return slowly to overhead.",
      "Repeat 10 times.",
    ],
    tips: "If you can't get far behind you, hold the towel wider. That makes the whole movement easier.",
    benefit: "Takes your shoulder through a wide range of motion in a controlled way.",
  },
  "shoulder-4": {
    title: "Shrug and Release",
    duration: "Hold 5 sec",
    reps: "20 reps",
    steps: [
      "Sit back in a chair or stand, arms hanging loose.",
      "Breathe in and shrug both shoulders up toward your ears as high as they go.",
      "Hold that squeeze for 5 seconds. Feel the muscles genuinely contract.",
      "Breathe out and drop your shoulders all at once — let them fall.",
      "Notice the warmth and the release in that moment.",
      "Repeat 20 times.",
    ],
    tips: "The contrast between the squeeze and the drop is the whole point. Pay attention to the letting-go.",
    benefit: "Contract-then-release resets muscles around the shoulders that have been holding tension all day.",
  },
  "shoulder-5": {
    title: "Wall Chest Opener",
    duration: "Hold 30 sec",
    reps: "3 sets each side",
    steps: [
      "Stand beside a wall so your right shoulder faces it.",
      "Place your right hand flat on the wall at shoulder height. A slight bend in the elbow is fine.",
      "Slowly rotate your body to the left, keeping your hand on the wall.",
      "Stop where you feel a good stretch across the front of your chest. Hold 30 seconds.",
      "Rotate back slowly and repeat on the other side for 30 seconds.",
      "One round each side is a set. Do 3 sets.",
    ],
    tips: "Especially useful if your shoulders sit forward. Changing the height of your hand changes where you feel it.",
    benefit: "Lengthens the chest muscles that pull your shoulders forward when you sit at a desk.",
  },

  // ========== Lower back ==========
  "back-1": {
    title: "Knees to Chest",
    duration: "Hold 30 sec",
    reps: "3 sets",
    steps: [
      "Lie on your back on a mat, arms and legs extended naturally.",
      "Slowly draw both knees toward your chest.",
      "Wrap your arms around your knees (or your shins) and hug them in.",
      "Your lower back will lift slightly off the floor. Hold 30 seconds and feel it lengthen.",
      "Extend your legs slowly back to the start and take three deep breaths.",
      "Repeat for 3 sets.",
    ],
    tips: "Keep your head on the floor so your neck stays relaxed. Keep breathing — don't hold your breath.",
    benefit: "Lengthens the muscles across the lower back, including the quadratus lumborum and the erector spinae.",
  },
  "back-2": {
    title: "Child's Pose",
    duration: "Hold 60 sec",
    reps: "2 sets",
    steps: [
      "Start kneeling, then open your knees slightly wider than your hips.",
      "Sit your hips back onto your heels.",
      "Breathe out and fold forward, bringing your forehead to the floor or mat.",
      "Extend both arms forward with your palms down.",
      "Breathe deeply for 60 seconds, feeling the length through your lower back, upper back and shoulders.",
      "Come back up to kneeling slowly and take three deep breaths. Repeat for 2 sets.",
    ],
    tips: "If your knees or hips complain, put a cushion under your knees. The deeper you breathe, the more your whole back opens on its own.",
    benefit: "Lengthens the lower back and the area around the sacroiliac joints. Slow breathing here also engages the parasympathetic nervous system, which is why it feels calming.",
  },
  "back-3": {
    title: "Cat & Cow",
    duration: "10 reps",
    reps: "3 sets",
    steps: [
      "Come onto hands and knees. Hands directly under your shoulders, knees under your hips.",
      "Breathe in and let your belly drop toward the floor, arching your back (Cow). Look up, tailbone lifts.",
      "Hold 2 seconds, then breathe out and slowly round your back (Cat).",
      "Draw your navel up toward your spine, look down, and round as far as you comfortably can.",
      "Arch and round together count as one rep. Do 10.",
      "Do 3 sets.",
    ],
    tips: "Sync the movement with your breath — that's what makes this work. Move slowly and use your full range.",
    benefit: "Moves your spine one segment at a time, which is what keeps it mobile.",
  },
  "back-4": {
    title: "Hip Bridge",
    duration: "Hold 5 sec",
    reps: "15 reps x 3 sets",
    steps: [
      "Lie on your back and bend your knees. Feet hip-width apart, flat on the floor.",
      "Rest your arms beside your body, palms down.",
      "Squeeze your glutes and lift your hips slowly toward the ceiling.",
      "Stop when your shoulders, hips and knees form a straight line. Squeeze harder and hold 5 seconds.",
      "Lower slowly and stop just before your hips touch the floor, then go again.",
      "15 reps is a set. Rest 30 seconds between sets and do 3.",
    ],
    tips: "Don't over-arch your lower back. Use your glutes and your abdominals together.",
    benefit: "Builds strength through the glutes, lower back and core — the muscles that hold your posture up all day.",
  },
  "back-5": {
    title: "Hamstring Stretch",
    duration: "30 sec each side",
    reps: "2 sets",
    steps: [
      "Lie on your back with both knees bent. A towel nearby makes this easier.",
      "Raise your right leg slowly toward the ceiling. A slight bend in the knee is fine.",
      "Hold the back of your right thigh (or your calf) with both hands and draw it toward you. You can also loop a towel around your foot.",
      "Feel the stretch down the back of your thigh. Hold 30 seconds.",
      "Lower slowly and repeat with the left leg for 30 seconds.",
      "One round each side is a set. Do 2 sets.",
    ],
    tips: "Don't force the knee straight. Wherever the back of the thigh feels a good stretch is far enough.",
    benefit: "Lengthens the hamstrings, which pull on the pelvis and change how your lower back sits when they're tight.",
  },

  // ========== Rounded upper back ==========
  "kyphosis-1": {
    title: "Chest Opener (Hands Clasped Behind)",
    duration: "Hold 30 sec",
    reps: "3 sets",
    steps: [
      "Stand tall with your feet hip-width apart.",
      "Clasp your hands behind your back. If you can't reach, hold the ends of a towel instead.",
      "Breathe in and draw your hands back, pulling your shoulder blades toward the center of your back.",
      "Open your chest forward. Keep your chin slightly tucked and lift only your eyes toward the ceiling.",
      "Hold 30 seconds where you feel a strong stretch across the front of your chest. Keep breathing.",
      "Lower your arms slowly and take a deep breath. Do 3 sets.",
    ],
    tips: "Keep a little tension in your abdominals so your lower back doesn't over-arch.",
    benefit: "Lengthens the chest and front-of-shoulder muscles that pull the shoulders forward when you sit.",
  },
  "kyphosis-2": {
    title: "Wall Stand",
    duration: "Hold 1 min",
    reps: "3 sets",
    steps: [
      "Stand with your back to a wall. Touch four points to it: back of your head, both shoulders, hips and heels.",
      "Tuck your chin slightly and look straight ahead. Ear, shoulder and hip should stack in a line.",
      "Ideally there's about one palm-width of space between your lower back and the wall.",
      "Hold this position for 1 minute, breathing naturally.",
      "Step away and try to keep the same feeling in your body.",
      "Rest 30 seconds and repeat. Do 3 sets.",
    ],
    tips: "Do this daily and your body starts to remember the position on its own. It fits into any spare minute.",
    benefit: "Gives your body a clear physical reference for upright standing that carries over into daily life.",
  },
  "kyphosis-3": {
    title: "Shoulder Blade Squeeze (Hold)",
    duration: "Hold 10 sec",
    reps: "15 reps",
    steps: [
      "Sit toward the front of a chair with your spine tall. Feet hip-width apart, flat on the floor.",
      "Raise both arms out to the sides at shoulder height and bend the elbows to 90 degrees.",
      "With palms facing forward, draw your elbows back.",
      "Squeeze your shoulder blades toward your spine and open your chest.",
      "Hold 10 seconds. Keep your shoulders down — don't let them creep up.",
      "Release slowly. Repeat 15 times.",
    ],
    tips: "Imagine holding a pencil between your shoulder blades — that's the squeeze you want.",
    benefit: "Strengthens the rhomboids between your shoulder blades, the muscles that hold your upper back upright.",
  },
  "kyphosis-4": {
    title: "Upper Back Release (Rolled Towel)",
    duration: "Hold 1 min",
    reps: "2 sets",
    steps: [
      "Roll a bath towel into a tube about 10 cm across. Two tennis balls work too.",
      "Lie on your back and place the roll under your upper back, between the shoulder blades.",
      "Open your arms wide to the sides with palms up, making a T shape.",
      "Knees can be bent. Breathe deeply and notice your chest opening over the roll.",
      "Hold 1 minute. Enjoy the stretch through your chest and upper back.",
      "Roll off slowly and take a deep breath. Do 2 sets.",
    ],
    tips: "Tennis balls are intense. If this is new to you, start with the towel.",
    benefit: "Restores movement to the thoracic spine — the section of your back that stiffens most from sitting.",
  },
  "kyphosis-5": {
    title: "Chin Tuck (Seated or Standing)",
    duration: "Hold 5 sec",
    reps: "20 reps",
    steps: [
      "Sit or stand with your spine tall.",
      "Imagine a string lifting the crown of your head toward the ceiling. Keep your neck long.",
      "Slide your head straight back, as if tucking your chin. Draw it back, not down.",
      "Feel the back of your neck lengthen — a slight double chin is correct. Hold 5 seconds.",
      "Release slowly back to the start.",
      "Repeat 20 times.",
    ],
    tips: "If you spend a lot of time looking down at a phone, this one is for you. Do it every day.",
    benefit: "Works the deep neck flexors that bring your head back over your shoulders after hours of screen time.",
  },

  // ========== Headache ==========
  "headache-1": {
    title: "Temple Massage",
    duration: "1 min",
    reps: "3 sets",
    steps: [
      "Sit back in a chair, close your eyes and relax.",
      "Place the index, middle and ring fingers of each hand gently on your temples.",
      "Using the pads of your fingers, make small clockwise circles for 30 seconds. Firm enough to feel good, never painful.",
      "Switch to counter-clockwise circles for another 30 seconds.",
      "Keep your breathing slow and deep. Notice the tension leaving your head.",
      "Rest 30 seconds to 1 minute. Do 3 sets.",
    ],
    tips: "Gentle stroking works better than hard pressing. Relaxing is the whole point.",
    benefit: "Loosens the temporalis muscles at the sides of your head, which tighten when you clench or concentrate.",
  },
  "headache-2": {
    title: "Base-of-Skull Release",
    duration: "30 sec",
    reps: "3 sets",
    steps: [
      "Sit back in a chair and bring both hands to the back of your head.",
      "Place your thumbs in the two hollows where your skull meets your neck, one on each side.",
      "Let the weight of your head rest onto your thumbs and press slowly.",
      "Hold 30 seconds at a firm-but-comfortable pressure. Keep breathing deeply.",
      "Release slowly and gently turn your head side to side.",
      "Rest 30 seconds. Do 3 sets.",
    ],
    tips: "These are the suboccipital muscles — small muscles that hold a lot of tension. Take your time here.",
    benefit: "Releases the small muscles at the base of the skull that stay contracted during long hours at a screen.",
  },
  "headache-3": {
    title: "Around-the-Eye Pressure Points",
    duration: "5 sec each",
    reps: "5 points x 3 rounds",
    steps: [
      "Point 1 — inner brow: press up into the hollow under the inner end of each eyebrow with your thumbs for 5 seconds.",
      "Point 2 — mid brow: press the hollow directly below the middle of each eyebrow with your middle fingers for 5 seconds.",
      "Point 3 — outer brow: press the hollow just past the outer end of each eyebrow for 5 seconds.",
      "Point 4 — outer eye: press the hollow one thumb-width out from the outer corner of each eye for 5 seconds.",
      "Point 5 — inner eye: gently press the small hollow just above the inner corner of each eye with your thumbs for 5 seconds.",
      "Five points make one round. Do 3 rounds.",
    ],
    tips: "The skin around your eyes is delicate. Use only as much pressure as feels pleasant.",
    benefit: "Encourages circulation around the eyes and eases the tightness that builds up from focusing on a screen.",
  },
  "headache-4": {
    title: "Front-of-Neck Stretch",
    duration: "Hold 20 sec",
    reps: "5 reps",
    steps: [
      "Sit back in a chair with your spine tall and shoulders relaxed.",
      "Place both hands just below your collarbones and press the skin gently downward.",
      "Slowly tip your head back and point your chin toward the ceiling.",
      "Feel the stretch down the front of your neck, from throat to collarbone. Hold 20 seconds.",
      "Return your head slowly and take one deep breath.",
      "Repeat 5 times.",
    ],
    tips: "Don't tip so far back that the back of your neck feels compressed. Comfort first.",
    benefit: "Lengthens the sternocleidomastoid at the front of the neck, a muscle that often tightens alongside head tension.",
  },
  "headache-5": {
    title: "Shoulder Blade Circles",
    duration: "30 sec",
    reps: "3 sets",
    steps: [
      "Sit back in a chair and place each hand on the same-side shoulder (right hand on right shoulder, left on left).",
      "Lift your elbows forward and up, then back and down, drawing big circles.",
      "Circle forward 5 or 6 times over 30 seconds.",
      "Reverse direction (back to front) for another 30 seconds, 5 or 6 circles.",
      "Feel your shoulder blades gliding across your upper back.",
      "Do 3 sets.",
    ],
    tips: "Move the shoulder blades, not just the shoulders. Make the circles as big as you comfortably can.",
    benefit: "Gets the whole upper back moving and blood flowing after a long stretch of sitting still.",
  },

  // ========== Eye strain ==========
  "eye-1": {
    title: "Blink Squeeze",
    duration: "1 min",
    reps: "3 sets",
    steps: [
      "Sit tall in a chair and relax.",
      "Squeeze both eyes shut tightly for 3 seconds. Feel the muscles around your eyes engage.",
      "Open your eyes as wide as you can for 3 seconds. Lifting your eyebrows helps.",
      "Squeeze then open counts as one. Do 10.",
      "Close your eyes and rest for about 30 seconds. If your eyes water a little, that's a good sign.",
      "Do 3 sets.",
    ],
    tips: "Especially useful between stretches of computer or phone work.",
    benefit: "Stimulates tear production and moves the muscles around the eyes that go still while you stare at a screen.",
  },
  "eye-2": {
    title: "Near-Far Focus",
    duration: "1 min",
    reps: "5 sets",
    steps: [
      "Sit in a chair and hold your thumb up about 20 cm in front of your face.",
      "Focus hard on your thumbnail for 3 seconds until it's sharp.",
      "Switch your gaze to something more than 3 meters away — out a window is ideal — for 3 seconds.",
      "Back to your thumb, then far again. Continue for 1 minute.",
      "That's one set. Rest 30 seconds between sets and do 5.",
      "A few times a day, especially after long desk sessions, is a good rhythm.",
    ],
    tips: "Focus on getting each image genuinely sharp, not on switching quickly.",
    benefit: "Exercises the ciliary muscle that changes your eye's focus, which locks up when you stare at one distance.",
  },
  "eye-3": {
    title: "Eye Circles",
    duration: "30 sec each direction",
    reps: "2 sets",
    steps: [
      "Sit in a chair facing forward. Keep your head completely still — only your eyes move.",
      "Look up for 3 seconds, down for 3, right for 3, left for 3.",
      "Now roll your eyes in a slow, large clockwise circle — 2 or 3 circles over 30 seconds.",
      "Reverse to counter-clockwise for 30 seconds, 2 or 3 circles.",
      "Close your eyes and rest for 30 seconds.",
      "Do 2 sets.",
    ],
    tips: "Imagine your chin is fixed in place so your head doesn't follow your eyes.",
    benefit: "Moves the six small muscles that steer each eye through their full range.",
  },
  "eye-4": {
    title: "Warm Towel",
    duration: "5 min",
    reps: "Once",
    steps: [
      "Wet a hand towel and wring it out firmly.",
      "Heat it in a microwave (500 W) for 30 to 40 seconds. Be careful — it can get hot.",
      "Test the temperature with your hand. Around 40 to 45 C — warm, never hot — is right.",
      "Sit back in a chair or lie down, close your eyes, and lay the towel gently over them.",
      "Relax for 5 minutes. Breathe deeply and feel the warmth around your eyes.",
      "When the towel cools, remove it and gently massage around your eyes to finish.",
    ],
    tips: "A towel that's too hot can burn. Always check it with your hand before it touches your face.",
    benefit: "Warmth increases blood flow around the eyes and relaxes the muscles that tighten during screen time.",
  },
  "eye-5": {
    title: "Inner-Eye Pressure Point",
    duration: "10 sec",
    reps: "5 reps",
    steps: [
      "Bring both hands to your face and close your eyes.",
      "Find the small hollow just above the inner corner of each eye, beside the bridge of your nose.",
      "Place the pad of each index finger (or thumb) there.",
      "Press slowly toward the inner corner of the eye and hold 10 seconds — firm but comfortable.",
      "Release slowly and take one deep breath.",
      "Repeat 5 times.",
    ],
    tips: "This is a delicate spot. Use the pad of your finger, never the nail, and don't press hard.",
    benefit: "A simple way to bring circulation and a feeling of relief to tired eyes after close-up work.",
  },
};
